### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by zytskymaker** [csi-greifflab/Absolut#12]
when i run this command:
`./AbsolutNoLib info_filenames 1FBI_X
wget http://philippe-robert.com/Absolut/Structures/SULSU040643e2c0a6d6343bbe8a27b079ef91-10-11-efc862c2cdef086ba79606103a3dfc62Structures.txt`
it reported error: 404 not found
How do i solve this problem?

**Comment by petouzeman** [comment]
Sorry for delay, we do not receive notifications from github, 

In theory, your problem is solved in the new versions of Absolut, where you have "https://ns9999k.webs.sigma2.no/10.11582_2021.00063/projects/NS9603K/pprobert/AbsolutOnline/Structures/"" instead, in lines 1918 and 1970 of file delimain.cpp. 

Tell us if the problem persists!

Best, 
philippe [dot] robert [at] ens [minus] lyon [dot] org
